// <auto-generated />
namespace MvcCompanySample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DocumentsDatabaseCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocumentsDatabaseCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201407260028318_DocumentsDatabaseCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
